# Generated by Django 5.2.3 on 2025-06-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('suppliers', '0002_alter_supplier_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='category',
        ),
        migrations.AddField(
            model_name='supplier',
            name='categories',
            field=models.ManyToManyField(related_name='suppliers', to='catalogos.categoriaproducto'),
        ),
    ]
